//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNT_TYPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ACCOUNT_TYPE()
        {
            this.BANKACCOUNTs = new HashSet<BANKACCOUNT>();
        }
    
        public decimal ACC_TYPE_ID { get; set; }
        public string ACC_TYPE_DESC { get; set; }
        public Nullable<decimal> MIN_BAL { get; set; }
        public Nullable<decimal> INTEREST_RATE { get; set; }
    
        public virtual ACCOUNT_TYPE ACCOUNT_TYPE1 { get; set; }
        public virtual ACCOUNT_TYPE ACCOUNT_TYPE2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BANKACCOUNT> BANKACCOUNTs { get; set; }
    }
}
