//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CUSTOMER()
        {
            this.BANKACCOUNTs = new HashSet<BANKACCOUNT>();
        }
    
        public decimal CIF { get; set; }
        public string CUSTOMER_TITLE { get; set; }
        public string CUSTOMER_FNAME { get; set; }
        public string CUSTOMER_LNAME { get; set; }
        public Nullable<System.DateTime> CUSTOMER_DOB { get; set; }
        public string CUSTOMER_EMAIL { get; set; }
        public Nullable<decimal> CUSTOMER_PHONE { get; set; }
        public string CUSTOMER_GENDER { get; set; }
        public string CUSTOMER_ADDRESS { get; set; }
        public string CUSTOMER_CITY { get; set; }
        public string CUSTOMER_STATE { get; set; }
        public Nullable<decimal> CUSTOMER_ZIPCODE { get; set; }
        public string IDPROOF_TYPE { get; set; }
        public Nullable<decimal> IDPROOF_NUMBER { get; set; }
        public string ADDRESSPROOF_TYPE { get; set; }
        public Nullable<decimal> ADDRESSPROOF_NUMBER { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BANKACCOUNT> BANKACCOUNTs { get; set; }
    }
}
