//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSACTION
    {
        public decimal TRANS_ID { get; set; }
        public Nullable<decimal> BRANCH_CODE { get; set; }
        public Nullable<decimal> ACCOUNT_NO { get; set; }
        public string TRANS_TYPE { get; set; }
        public System.DateTime TRANS_DATE { get; set; }
        public string TRANS_DESC { get; set; }
        public Nullable<decimal> TRANS_AMOUNT { get; set; }
    
        public virtual BANKACCOUNT BANKACCOUNT { get; set; }
        public virtual BRANCH BRANCH { get; set; }
    }
}
